-- MLIT sample CPL airplane 2026-06
-- Generated by import_mlit_sample_to_unified.py
-- Count: 74
BEGIN;

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '機首にプロペラを備えた単発機で、プロペラ回転後流の影響を打ち消すための一般的な方法（a） ～（d）のうち、正しいものはいくつあるか。（1）～（5）の中から選べ。 （a）垂直尾翼の断面を対称形にせずキャンバを与える。 （b）垂直尾翼に取付角を持たせる。 （c）方向舵の断面を非対称にする。 （d）エンジンを右または左に向けて取り付ける。',
  '["1 つ", "2 つ", "3 つ", "4 つ"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 2, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '翼型の一般的な特性に関する説明（a）～（d）のうち、正しいものはいくつあるか。（1）～（5） の中から選べ。 （a）翼厚の薄い翼型は迎え角を大きくすると流れの剥離が起きやすく、抗力の急激な増大を招き やすい。 （b）前縁半径が大きい翼型は流れが前縁を回りやすいため、最大迎え角が大きくできる。 （c）対称翼は迎え角をゼロとした場合でも、ある程度の揚力係数をもつ。 （d）キャンバが大きくなるほど揚力係数は大きくなる。',
  '["1 つ", "2 つ", "3 つ", "4 つ"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 3, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '揚力の一般的な理論に関する記述（a）～（d）のうち、正しいものはいくつあるか。（1）～（5） の中から選べ。 （a）翼面積が２倍になると揚力は４倍になる。 （b）揚力は空気密度に反比例する。 （c）揚力は速度の２乗に反比例する。 （d）揚力は揚力係数に比例する。',
  '["1 つ", "2 つ", "3 つ", "4 つ"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 4, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '層流と乱流の特性（a）～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中から選 べ。 （a）層流は乱流よりも摩擦抗力がはるかに小さい。 （b）乱流は層流よりも境界層が厚い。 （c）乱流中では流速は規則的に変化しているが、層流中では流速の変化は不規則である。 （d）層流では隣り合った層との間でエネルギーの授受は行われないが、乱流ではエネルギーの授 受が行われる。',
  '["1 つ", "2 つ", "3 つ", "4 つ"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 5, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '安定性の説明（a）～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中から選 べ。 （a）外力により機体の姿勢が変化したとき、元の姿勢に戻そうとする復元力が生ずるかどうか という性質を静安定という。 （b）外力により飛行姿勢が変化したとき、時間の経過とともに復元力に減衰力が作用して動揺 の振幅が次第に変化していく性質を動安定という。 （c）動安定には「正・中立・負」があるが、静安定には「正・負」しかない。 （d）静安定が正の場合、動安定が負になることはない。',
  '["1 つ", "2 つ", "3 つ", "4 つ"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 6, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  'トリム・タブについての説明で誤りはどれか。',
  '["舵の効きを増加させるため、タブを舵面と同じ方向に動かす。", "与えられた飛行状態を維持するための保舵力をゼロにする働きがある。", "トリム・ホイール、ハンドル、またはスイッチによって操縦装置の舵面とは別に動かされ る。", "高速機では、衝撃波の影響を小さくするためにタブの代わりに水平安定版を動かす方法が 使われる。"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 7, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '方向舵についての説明（a）～（d）のうち、正しいものはいくつあるか。（1）～（5）の中から選 べ。 （a）偏揺れモーメントを制御する舵面である。 （b）きりもみ状態からの回復に用いられる。 （c）アドバース・ヨーを打ち消すために用いられる。 （d）方向舵の失速を防ぐため、垂直尾翼は縦横比を大きくしている。',
  '["1 つ", "2 つ", "3 つ", "4 つ"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 8, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  'プロペラへの着氷及び防除氷に関する記述（a）～（d）のうち、正しいものはいくつあるか。（１） ～（５）の中から選べ。 （a）プロペラブレードの断面は翼型をしているため、ブレード前縁部に着氷する。 （b）防除氷の方法として、防氷液を各ブレード前縁部へ流す化学的な方法がある。 （c）防除氷の方法として、ブレード前縁部にヒーターをはり付ける電気的な方法がある。 （d）プロペラへの着氷は推進効率（推力馬力/軸馬力）を低下させ、プロペラに不規則振動を発生 させる。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 12, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '電離層についての説明で誤りはどれか。',
  '["夏期には、E 層とほぼ同じ高さに、電子密度の高いスポラディック E 層がよく出現する。", "HF（短波）帯の電波は D、E 層を突き抜け、F 層で反射される。", "VHF（超短波）帯以上ではすべて電離層で反射される。", "電離層の電子密度は、太陽の活動と密接な関係がある。"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 17, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '航空燃料（ガソリン）のベーパ・ロック現象に関する記述で誤りはどれか。',
  '["燃料は、ある条件下では、配管・ポンプおよびその他の部品の内部で気化する。その結 果、発生する燃料の流れの部分的な、あるいは完全な途絶をベーパ・ロックという。", "ベーパ・ロックは、燃料を遮断してエンジンを停止させるほど重大事になることがあり、 燃料配管中の小さなベーパでさえ、主燃料ポンプへの燃料の流れを制限して吐出圧力を減ら す。", "ベーパ・ロックの発生原因には、燃料にかける圧力の低下、燃料温度の上昇および、燃料 の過度のかく乱がある。", "ベーパ・ロックを減少させるための最大の改善は、燃料系統にフューエル・ストレーナを 組み込むことである。これによってベーパの形成を減らし、かつベーパの空洞を移動させる のに役立つ。"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 18, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '航空機の自重に含まれるもの（a）～（d）のうち、正しいものはいくつあるか。 （１）～ （５）の中から選べ。 （a） 使用不能燃料 （b） 滑油 （c） 動力装置 （d） 固定バラスト',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 19, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空工学',
  'CBT例題/未分類',
  '重量 2,200 lb、重心位置が基準線後方 41 in の飛行機の重心位置を、 100 lb の荷物を積むこと によりあと 3 in 後方に移したい。荷物を積む位置で正しいものはどれか。',
  '["基準線後方 25 in", "基準線後方 39 in", "基準線後方 42 in", "基準線後方 110 in"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 20, "main_subject": "航空工学", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空工学', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '方位について誤りはどれか。',
  '["真方位は、現在地点を通る子午線の真北（地軸の北）を基準にして現在地点とある地点を 結んだ線となす水平面上の角度のことである。", "真針路とは、航空機の機首の向いている方向の磁方位で、機位を通る子午線の磁北から測 ったものである。", "航跡は、航空機が地表上を飛行した軌跡の真方位である。航跡の測定は常にその時々の機 位を通る子午線の真北から測る。", "相対方位とは、航空機からある地点への方向を機首尾線から時計回りに３６０度まで測っ た水平角度である。"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 1, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '地文航法の説明で正しいものはどれか。',
  '["飛行中の風を求め、針路の決定や速度と経過時間により位置を推測しながら飛行する方法 である。", "航法援助施設からの電波を受信して位置や針路を求めて飛行する方法である。", "地形地物と地図を見比べながら飛行する方法である。", "管制機関と通信を設定し、常に管制機関の指示に従って飛行する方法である。"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 2, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '緯度について正しいものはどれか。',
  '["緯度 1°は約 1 nm である。", "緯度 1°は約 1 km である。", "緯度 1°は約 60 nm である。", "緯度 1°は約 60 km である。"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 4, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  'メルカトル図及びランバート図についての記述（a）～（d）のうち、正しいものはいくつあるか。 （ 1 ） ～（ 5 ） の中から選べ。 （a）メルカトル図における緯度の間隔は緯度が高くなるほど大きくなる。 （b）メルカトル図における子午線は平行で直線は航程線になる。 （c）ランバート図における子午線と平行圏は直交している。 （d）ランバート図における直線は大圏と見なして実用上差し支えない。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 5, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}, "notes": "figure_in_original_pdf"}'::jsonb,
  3,
  6.0,
  1,
  'pending',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample', '要図']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '風力三角形について誤りはどれか。',
  '["TH と TR の成す角度を偏流角 DA という。", "対気ベクトルは TR と GS からなる。", "風向と風速が一定の場合、TAS が遅くなると DA は大きくなる。", "DA は機体の大きさには関係しない。"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 6, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  'ランバート図上で航程線コースの真方位を最も正確に測定する方法で正しいものはどれか。',
  '["どこの子午線を使用してもよい。", "出発地に近い子午線を使用する。", "目的地に近い子午線を使用する。", "コースの中分子午線もしくは中間付近の子午線を使用する。"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 7, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '野外飛行において巡航中、計画通り WCA＋10°として飛行していたところ、機軸線上にある前 方の目標物が機軸線に沿って真っすぐ近づいてきた。この時の WCA について正しいものはどれ か。',
  '["大きすぎる。", "小さすぎる。", "適切である。", "チェックポイントまで判断できない。"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 8, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '偏差・自差についての記述（a）～（d）のうち、正しいものはいくつあるか。 （ 1 ） ～ （ 5 ） の中から選べ。 （a）真北に対して磁北が西を指していれば偏差 W という。 （b）磁北に対して羅北が西を指していれば自差 W という。 （c）日本付近の偏差は 6°～8°E であるが、年月と共に変化していて流動的である。 （d）適切に整備された磁気羅針儀であれば自差が生じることはない。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 9, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '会合法の原則で誤りはどれか。',
  '["会合の運動中は変針、変速しない。", "会合時刻に会合点へ到着するため速度を常に変更する。", "両者の行動開始時刻が同時刻である。", "行動開始時の相対方位を一定に保つ。"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 10, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  'RNAV（広域航法）に関する記述（ａ）、（ｂ）、（ｃ）について、正しい記述はいくつあるか。（１） ～（４）の、中から選べ。 （ａ）RNAV に基づく航法は、出発、巡行、到着、進入のすべての飛行フェーズにおいて行うこ とができる。 （ｂ）RNAV 経路における運航においては、経路に対する航法上の誤差は、全飛行時間中 99.7% は航法仕様で示された数値の範囲になければならない。 （ｃ）RNAV5 経路を航行するためには、常にレーダーによる監視を受ける必要がある。',
  '["１つ", "２つ", "３つ", "無し"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 11, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '空港進入前に入手した QNH 29.85 inHg に対し、誤って 29.95 inHg の値を気圧高度計にセット し場周経路に進入した。場周経路下の標高が 200 ft のところを、計器高度 1,200 ft で飛行した場 合、場周経路下の標高からの対地高度に最も近いものはどれか。',
  '["900 ft", "990 ft", "1,100 ft", "1,190 ft"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 12, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '耳閉塞について誤りはどれか。',
  '["風邪やのどの痛みあるいは鼻アレルギーの状態にあると耳管の周りが充血して通気が困難 になり、その結果中耳と外気の気圧差が増大する。これが耳閉塞である。", "水泳後に耳に水が溜まり、それを抜かずに飛行した場合、耳垢がふやけて鼓膜外側に張り 付き耳閉塞になることもある。", "鼓膜を介した圧力差は中耳が炎症する航空性中耳炎につながることがあるが、聴力の低下 につながるおそれはない。", "着陸後しばらくたっても耳閉塞が治まらないときは医師に相談すべきである。"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 13, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '低酸素症に関する記述で、誤りはどれか。',
  '["大気中に酸素の占める割合は地上からはるか上空に上昇するに従い減少することから、飛 行高度の増大に対応して低酸素症の傾向は増大する。", "低酸素状態は夜間視力に影響する。", "低酸素症の影響を認知することは通常大変難しい。", "低酸素症の発生は酸素吸入、または、与圧圧力を適切にコントロールすることにより防止 できる。"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 14, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '暗順応について誤りはどれか。',
  '["暗順応を得るためには真暗闇の中で少なくとも 30 分を要する。", "赤色光では機内の目標物に眼の焦点を合わせることが甚だしく困難となる。", "暗順応性は機内気圧高度が 10,000 フィートを超えるとき、喫煙や排気ガスによる一酸化 炭素中毒、食物によるビタミン A の欠乏および直射日光への長時間の露出などによって損 なわれる。", "わずか 2～3 秒間明るい光を見るだけで暗順応性は全て失われる。"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 15, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  'パイロットの航空業務に与える影響について誤りはどれか。',
  '["日常生活の中では軽い病気とされるものであれば、安全な航空業務の遂行能力への影響は ほとんどない。", "病気にかかって薬を服用することは、それが処方によるものであっても、かかった病気の 症状と同じ程度にパイロットの能力を低下させてしまうことがある。", "日常生活のプレッシャーからくるストレスは、様々な観点からパイロットの能力に悪い影 響を与える。", "アルコールは、パイロットに錯覚を起こさせ易く、また呼吸を抑制する影響で酸欠耐性を も弱化させる。"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 16, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  'アルコールの飲用が飛行に及ぼす影響について誤りはどれか。',
  '["中程度のアルコール量が体内で完全に消滅した後でも、二日酔いの影響でかなりの時間に わたって著しい能力低下が続く。", "アルコールはパイロットに錯覚を起こさせ易い。", "呼吸を抑制する影響で、酸欠耐性をも甚だしく弱化させてしまう。", "アルコールの分解速度は、性別・年令・体重・体質により異なるが、 疲労・体調等では 変動しない。"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 17, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  '航空医学に関する記述で誤りはどれか。',
  '["世界保健機関は、「健康」を「単に身体的機能が正常であるだけでなく、精神的、社会的 にも正常であること」と定義している。健康ではない状態で航空機を操縦することは、パイ ロットインキャパシテーションに繋がり得る。", "暖房装置のない小型機では、低体温症になりやすい。", "血液中のブドウ糖（血糖値）が低下すると一般にイライラするが、判断力や注意力は高ま り、ヒューマンエラーを発生させることはない。", "過呼吸と低酸素症は、初期の兆候がよく似ており、さらに同時に発生することもある。"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 18, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  'ヒューマンファクターの SHEL モデル構成要素について、誤りはどれか。',
  '["S＝Software", "H＝Human", "E＝Environment", "L＝Liveware"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 19, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '空中航法',
  'CBT例題/未分類',
  'TEM（Threat and Error Management）にある UAS（Undesired Aircraft State）に関して次 の（ａ）、（ｂ）について、その正誤の組み合わせとして正しいものはどれか。 （ａ）乗員自身、または組織の意図や期待から逸脱し、安全マージンを減少させ、運航を悪化さ せる事態が発生する可能性を高めるものをいう。 （ｂ）乗員のエラーや行動、あるいは行動の欠落により、安全マージンが低下している状態をい う。',
  '["（ａ）誤 （ｂ）誤", "（ａ）誤 （ｂ）正", "（ａ）正 （ｂ）誤", "（ａ）正 （ｂ）正"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 20, "main_subject": "空中航法", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '空中航法', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '地球の大気に含まれる水蒸気について（a）～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中から選べ。 （a）水蒸気は気体状態の水であり、目で確認できる物質なので視程障害現象をもたらす。 （b）水蒸気は雲、雨、雪の元になる。 （c）水蒸気はエネルギー（潜熱）の運び手である。 （d）水蒸気は地球温度の調整役（温室効果）の働きがある。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 1, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '大気の気温による鉛直分布の分類で対流圏と成層圏について（a）～（d）のうち、正しいものは いくつあるか。 （１）～（５）の中から選べ。 (a) 地表面から気温が高度とともに減少していく範囲を対流圏といい、地表面は大気を透過した 太陽光線により加熱されることで熱源となり、上空へ熱の反射を行う。 (b) 対流圏では上下の気流の対流が盛んに起こり、雲や雨など天気に密接な関係をもっている。 (c) 成層圏は対流圏の直ぐ上にあり、成層圏下部では温度はほとんど一定(-50℃程度）であるが、 高度 20km 以上では上昇に転じ、約 50km でピークに達する。 (d) 成層圏上部が下部より気温が高いのは、成層圏にある上部の水蒸気が太陽からの紫外線を吸 収するためにおこる。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 2, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '比熱について（a）～（d）のうち、正しいものはいくつあるか。（１）～（５）の中から選べ。 （a）単位質量のある物質の温度を１℃だけ上げるのに必要な熱量のことである。 （b）水の比熱は１cal/g である。 （c）比熱の小さい物体は、暖まりやすく冷えやすい。 （d）陸地を形成する岩石や土壌の比熱は水より大きく、陸地面は海水面よりも暖まりにくく冷 めにくい。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 3, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '対流圏における逆転層の成因と特徴について（a）～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中から選べ。 （a）冷気の上に暖気が重なって前線面を作る場合にできる逆転で、前線の存在により下層に寒気、 上層に暖気がくるために発生する前線性逆転がある。 （b）晴れた日などで夜間放射によって地表面の気層が冷却されてできる接地逆転がある。接地逆 転は放射性逆転ともいう。この逆転層は地面から形成され、あまり上空までは発達せず、朝 になって太陽の熱が地面に加わると逆転は解消する。 （c）高気圧の下降気流により空気が沈降し、断熱圧縮の昇温によって地表面から離れた高度にで きる。高気圧下なので通常は晴天であり、上層の乾燥空気で形成されるので逆転層の気温と 露点温度の差は下層に比べて大きく開いている。 （d）対流圏では上空ほど気温が低くなるのが通常であるが、時に上の方が下よりも暖かい層が発 生することがある。これを逆転層という。逆転層では対流が起こらず大気は安定している。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 4, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '空気塊が断熱変化するときの温度変化について（a）～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中から選べ。 (a) 大気が上昇して飽和に達する直前までの気温減率を湿潤断熱減率という。 (b) 飽和した空気塊が断熱的に上昇するときの温度の減少率を乾燥断熱減率という。 (c) 湿潤断熱減率が乾燥断熱減率に比べて小さいのは、水蒸気の気化により放出された熱を大気が 吸収するため大気温度が上昇することによる。 (d) 湿潤断熱減率は気温が高いほど小さい。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 5, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  'ショワルター指数について（a）～（d）のうち、正しいものはいくつあるか。 （1）～（5）の中 から選べ。 (a) 500hPa より下方の下層大気の安定度を知る一つの方法である。 (b) 850hPa の空気塊を 500hPa まで上昇させたときの温度から 500hPa の高度に存在する空気の 温度を減じた値を指数としたものである。 (c) ショワルター指数は正の値が大きくなるほど不安定度は大きい。 (d) 夏の台風発生の良い目安となる。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 6, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '10 種雲形の名称と温帯地方によくあらわれる高さの組み合わせ（a）～（d）のうち、正しいもの はいくつあるか。（１）～（５）の中から選べ。 （a）巻 雲：上層 （b）巻積雲：中層 （c）高層雲：普通中層に見られるが、上層まで広がっていることが多い。 （d）積乱雲：雲底は普通下層にあるが、雲頂は中、上層まで達していることが多い。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 7, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '富士山のような孤峰による山岳波が存在するときにみられる雲（a）～（d）のうち、正しいもの はいくつあるか。 （１）～（５）の中から選べ。 （a）つばさ雲 （b）はた雲',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 8, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '摩擦層内の風についての説明で誤りはどれか。',
  '["摩擦層内では、風向は等高線と平行になる。", "摩擦層内では、風速は地衡風より小さくなる。", "地表面摩擦の影響は高度が上がるとともに小さくなる。", "地表面摩擦は地上 500～600m くらいまでの風速を弱めるのに効く。"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 9, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '前線に関する記述（a）～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中から選 べ。 （a）性質の違った二つの気団が隣り合ってできる不連続面を前線面と呼び、この前線面が地上と 交わる線を前線又はフロントという。しかし、この面または線とは、幾何学でいう厳密な面 または線でなく、ある厚さや幅を持っている。 （b）前線面のなす傾斜角はふつう１／５０から１／３００くらいの角度である。前線の傾斜が急 なほど、前線面に起こる空気の鉛直運動が強くなり、雲の発生、発達を促進するので天気へ の影響が大きいことになる。 （c）温暖前線とは寒気団側へ移動する前線のことであり、通常、前線の通過後に気温は上がる。 また、寒冷前線とは暖気団側へ移動する前線であり、通常、前線の通過後に気温は下がる。 （d）前線を境にして気温（密度）、水蒸気の量、風向、風速などの気象要素の幾つかが飛躍的に 異なっている。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 11, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '沿岸前線に関する説明（a）～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中か ら選べ。 （a）地上天気図には描かれない局地的な前線で、低気圧が接近するときに温暖前線の前面（寒気 側）で発生することが多い。 （b）陸上の薄い寒気層（北寄りの弱風）と、その上に流れ込む暖かい空気（南寄りの強風）の境 界に発生するため、前線近傍では風向きが急変するほか、気温の水平傾度が大きい。 （c）沿岸前線の陸側では、暖かく湿った気塊が寒気の上を滑昇するため層状雲が発生し、悪視程 と低シーリングが発生することが多い。沿岸前線近傍の下層では発達した対流雲が発生する こともある。 （d）薄い寒気とその上の暖気との間では風のシアーが大きく、波動が発生している場合がある。 特に、沿岸前線が空港の近くに存在し、上空では南風、空港の地上風は北寄りの風という状 況で南から空港へ進入する場合、かなりの低高度で低層ウィンドシアーや乱気流に遭遇する 可能性を考慮する必要がある。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 12, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}, "notes": "figure_in_original_pdf"}'::jsonb,
  3,
  6.0,
  1,
  'pending',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample', '要図']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '霧（fog）についての説明（a）～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中 から選べ。 （a）定時飛行場実況気象通報式（METAR）では FG で報じられる。 （b）視程障害現象の一つで、視程 1,000 m 以下の場合をいう。 （c）ごく小さな水蒸気が大気中に浮遊する現象である。 （d）霧の中の相対湿度は一般に 70 %前後であることが多い。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 16, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '次の運航用飛行場予報気象通報式（TAF）の説明（a）～（d）のうち、正しいものはいくつある か。 （１）～（５）の中から選べ。 RJFF 040513Z 0406 / 0512 12007KT 9999 -SHRA FEW015 SCT020 BKN040 BECMG 0413 / 0415 13015G30 KT TEMPO 0414 / 0416 3000 SHRA BR BKN015 TEMPO 0416 / 0421 1500 +SHRA BR BKN010 BECMG 0500 / 0503 30012 KT TEMPO 0503 / 0506 29015G25 KT （a）日本時間 4 日午後 9 時の風向風速 は 120 度 7 ノットが予想されている。 （b）日本時間 5 日午前 1 時には一時的に最大 30 ノットの風が予報されている。 （c）日本時間 5 日午前 5 時には一時的に強いしゅう雨が予報されている。 （d）日本時間 5 日午後 6 時には 300 度 12 ノットの風が予報されている。 （１）１つ （２）２つ （３）３つ （４）４つ',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 18, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  '次の表はアジア太平洋域の実況天気図で使用する海上警報の種類とその記号の説明を示したもの である。表の（a）～（e）の説明のうち、正しいものはいくつあるか。（１）～（５）の中から 選べ。 （a） 海上風警報 （b） GW （c） 海上暴風警報 （d） 台風による風が最大風速 48 ノット以上 （e） 視程（水平方向に見通せる距離） 0.5 海里（約 1,000 m）以下',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 19, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "５つ", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空気象',
  'CBT例題/未分類',
  'トラフの説明（a）～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中から選べ。 （a）トラフは一般に西から東へ移動する。 （b）トラフの前面は下降域であり一般的に天気は良い。 （c）偏西風中のトラフの移動速度は等高線と等温線の関係から推定される。 （d）等高線と等温線が同位相で、振幅が両方同じであればトラフは逆行する。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 20, "main_subject": "航空気象", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空気象', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '航空交通業務の目的で誤りはどれか。',
  '["走行区域を除き、空域においての航空機相互間の衝突を防止すること。", "円滑で秩序ある航空交通流を促進し維持すること。", "安全かつ効率的な飛行のために有用な情報と助言を与えること。", "捜索救難を必要とする航空機に関して適当な機関に通報するとともに、要請に応じて当該 機関を支援すること。"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 1, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '管制業務の主たる対象について誤りはどれか。',
  '["特別管制区内の有視界飛行方式による飛行", "管制圏内における特別有視界飛行方式による飛行", "管制圏内の有視界飛行方式による飛行", "情報圏内の有視界飛行方式による飛行"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 2, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '航空交通管制業務に含まれないのはどれか。',
  '["飛行場管制業務", "進入管制業務", "ターミナル・レーダー管制業務", "広域対空援助業務"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 3, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '航空機用救命無線機（ELT）に関して、次の（ａ）、（ｂ）について、その正誤の組み合わせとして 正しいものはどれか。 （ａ）ELT は、遭難や墜落あるいは不時着した航空機の位置を探知させるための信号を送信する 装置である。 （ｂ）ELT は、406 MHz で捜索救難衛星に識別符号を含むデータを送信し、121.5MHz で航空機 または救難用船舶向けに独自の信号音を送信する。 （１）（ａ）正 （ｂ）正 （２）（ａ）正 （ｂ）誤 （３）（ａ）誤 （ｂ）正 （４）（ａ）誤 （ｂ）誤',
  '["（ａ）正", "（ａ）正", "（ａ）誤", "（ａ）誤"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 4, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '有視界飛行方式の飛行計画の変更について誤りはどれか。',
  '["出発前に変更する場合、コールサインと変更内容のみを通報する。", "出発前に変更する場合、いずれかの空港事務所または出張所の運航情報機関に通報する。", "出発時刻が 30 分以上遅延する場合、管制機関または運航情報機関に通報すべきである。", "飛行中の航空機から飛行計画を変更することはできない。"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 8, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '航空保安無線施設の説明で誤りはどれか。',
  '["ILS(instrument landing system) は、最終進入中の航空機に滑走路に対する正確な進入 経路と降下角を示す施設である。", "DME(distance measuring equipment) は、航空機までの距離を測定しレーダー画面上に 表示する装置である。", "TACAN（tactical air navigation)の方位信号の作動原理は、VOR のそれとはまったく異 なったものであるが機上 DME 装置によってこの施設を DME 局として利用できる。", "VOR(VHF omni-directional radio range) は、超短波全方向式無線標識施設であり、基本 信号と方位による可変信号とを発射している。"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 10, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '広域対空援助局（AEIS）に関する記述で誤りはどれか。',
  '["新千歳、大阪、福岡、鹿児島および那覇の空港事務所に設置されており、コールサインは 「フライト・サービス」が使用される。", "飛行中の航空機からの位置通報、PIREP、飛行計画の変更等の運航援助を行う。", "航空機からの要求に応じた気象情報、航空情報等の提供を行う。", "航空機との通信は、空港事務所に設置された広域対空援助局が、各地に設置された通信サ イトを通じて行っている。"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 11, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '応答および復唱要領について誤りはどれか。',
  '["「roger」の用語は、「送信内容を受信した」という意味であり、その内容に対する肯定の 意味は含んでいない。したがって「yes」または「no」の意味で返答する必要のある場合は、 「affirm」または「negative」の用語を使用するべきである。", "無線電話による交信で、自局にあてられた通信を受信した場合、混信防止のため自局のコ ールサインは省略して送信しなければならない。", "リードバックは、送信内容の聞き違いを防ぎ、送信者によるダブルチェックにより、通信 内容を相互に確認するために重要である。しかしながら全ての通信の内容をリードバックするこ とは交信をいたずらに繁雑にし、通信量を増大させるのでかえって好ましくない。", "管制官から「read back」の指示を受けた場合は、通報されたクリアランス等を同じ用語 により同じ順番で復唱する。"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 14, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '特別有視界飛行方式の説明で正しいものはどれか。',
  '["許可は管制圏の指定されている飛行場においてのみ発出される。", "原則として IFR 機の航行に支障が無い場合に許可される。", "管制間隔で特定の高度指定は行われないが、IFR 機がある場合に限り IFR 機の下方 1,000 ft 以下の高度で飛行するよう指示される。", "地上視程が 1,500 m 未満の場合は、絶対に許可が発出されない。"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 17, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  '航空法施行規則第 209 条（位置通報）に定める通報しなければならない事項のうち誤りはどれ か。',
  '["当該航空機の登録記号又は無線呼出符号", "予報されない特殊な気象状態", "当該地点における時刻及び速度", "その他航空機の航行の安全に影響のある事項"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 18, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空通信',
  'CBT例題/未分類',
  'TCA（terminal control area）アドバイザリー業務で実施される業務のうち誤りはどれか。',
  '["レーダー交通情報の提供", "当該機の要求に基づくレーダー誘導", "当該機の位置情報の提供", "待機のための指示の発出"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 19, "main_subject": "航空通信", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空通信', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法施行規則第 97 条（航空保安無線施設の種類）に規定された航空保安無線施設の説明（a） ～（d）のうち、正しいものはいくつあるか。 （１）～（５）の中から選べ。 （a）VOR とは、航行中の航空機に対し当該施設を基準とする磁方位を提供する。 （b）タカンとは、航行中の航空機に対し当該施設を基準とする真方位を提供する。 （c）衛星航法補助施設とは、航行中の航空機に対し測位を補助するための信号を衛星経由送信 型衛星航法補助施設又は地上直接送信型衛星航法補助施設から送信する。 （d）DME とは、航行中の航空機に対し当該施設からの水平距離を提供する。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 1, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法第 2 条（定義）で定める条文（a）～（d）のうち、正しいものはいくつあるか。 （１）～ （５）の中から選べ。 （a）「航空機」とは、人が乗つて航空の用に供することができる飛行機、回転翼航空機、滑空機、 飛行船その他政令で定める無人航空機をいう。 （b）「着陸帯」とは、特定の方向に向かつて行う航空機の離陸（離水を含む。）又は着陸（着水を 含む。）の用に供するため設けられる空港その他の飛行場内の矩形部分をいう。 （c）「進入表面」とは、着陸帯の短辺に接続し、且つ、水平面に対し上方へ四十分の一以上で国土 交通省令で定める勾配を有する平面であつて、その投影面が進入区域と一致するものをいう。 （d）「航空機使用事業」とは、他人の需要に応じ、航空機を使用して有償で旅客又は貨物を運送 する事業をいう。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 2, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '有視界気象状態を維持しながら行う飛行（a）～（d）のうち、正しいものはいくつあるか。（１） ～（５）の中から選べ。 （a）3,000ｍ未満の高度で管制圏内を飛行する場合、飛行視程 5,000ｍ、航空機から雲までの水平 距離を 1,000ｍ、垂直距離を上方へ 300ｍ、下方へ 300ｍ確保しながら行う飛行 （b）3,000ｍ未満の高度で情報圏内を飛行する場合、飛行視程 1,500ｍ、航空機から雲までの水平 距離を 600ｍ、垂直距離を上方へ 150ｍ、下方へ 300ｍ確保しながら行う飛行 （c）管制圏、情報圏以外の空域を対地高度 150ｍを維持して飛行する場合、飛行視程 3,000ｍ、 航空機から雲までの水平距離を 300ｍ、垂直距離を上方へ 100ｍ、下方へ 100ｍ確保及び地 表または水面を引き続き視認しながら行う飛行 （d）管制区、管制圏、情報圏以外の標高 2,500ｍ未満の山岳地帯を対地高度 450ｍを維持して飛 行する場合、飛行視程 8,000ｍ、航空機から雲までの水平距離を 300ｍ、垂直距離を上方へ 150ｍ、下方へ 300ｍ確保しながら行う飛行',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 3, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '耐空証明に関する条文の記述で誤りはどれか。',
  '["耐空証明は、日本の国籍を有する航空機でなければ、受けることができない。ただし、政 令で定める航空機については、この限りでない。", "耐空証明は、航空機の型式及び国土交通省令で定める航空機の運用限界を指定して行う。", "航空機は、有効な耐空証明を受けているものでなければ、航空の用に供してはならない。 ただし、試験飛行等を行うため国土交通大臣の許可を受けた場合は、この限りでない。", "耐空証明の有効期間は、１年とする。ただし、航空運送事業の用に供する航空機について は、国土交通大臣が定める期間とする。"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 4, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法施行規則第 114 条に定める飛行場灯火の種類に関する記述（a）～（d）のうち、正しいも のはいくつあるか。 （１）～（５）の中から選べ。 （a）飛行場灯台 （b）航空路灯台 （c）進入灯台 （d）風向灯 （１）１つ （２）２つ （３）３つ （４）４つ',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 5, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '飛行場灯火の説明について（ a ）～（ d ）のうち、正しいものはいくつあるか。 （１）～ （５）の中から選べ。 （a） 進入灯：着陸しようとする航空機にその最終進入の経路を示すために進入区域内及び着陸 帯内に設置する灯火 （b） 滑走路末端灯：離陸し、又は着陸しようとする航空機に滑走路の末端を示すために滑走路 進入端及び滑走路終端に設置する灯火で非常用滑走路灯以外のもの （c） 接地帯灯：離陸し、又は着陸しようとする航空機に滑走路を示すためにその両側に設置す る灯火で非常用滑走路灯以外のもの （d） 停止線灯： 地上走行中の航空機に一時停止の要否及び一時停止すべき位置を示すために 設置する灯火',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 8, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法第 59 条（航空機に備え付ける書類）で定める書類のうち、「その他国土交通省令で定める 航空の安全のために必要な書類」について誤りはどれか。',
  '["運用限界等指定書", "飛行規程", "搭載用航空日誌", "飛行の区間、飛行の方式その他飛行の特性に応じて適切な航空図"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 10, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '救急用具について誤りはどれか。',
  '["救命胴衣又はこれに相当する救急用具は、各座席から取りやすい場所に置き、その所在及 び使用方法を旅客に明らかにしておかなければならない。", "救命ボートは、搭乗者全員を収容できるものでなければならない。", "救急箱には、医療品一式を入れておかなければならない。", "航空機に装備しなければならない救急用具は、点検の内容、方法その他の事項に関し製造 者がそれぞれ定める技術的基準により点検しなければならない。"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 11, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法施行規則第 150 条に定める救急用具に関する記述について誤りはどれか。',
  '["航空機用救命無線機は、121.5 メガヘルツの周波数の電波及び 406 メガヘルツの周波数の 電波を同時に送ることができるものでなければならない。", "救急箱には医療品一式を入れておかなければならない。", "複数の航空機用救命無線機を装備する場合そのひとつは、衝撃により自動的に作動するも のでなければならない。", "航空機用救命無線機は、連続して 24 時間作動するものでなければならない。"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 12, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法第 71 条の 5（技能発揮訓練）に定める技能発揮訓練を修了した者でなければ実施すること ができない行為はどれか。',
  '["航空交通管制圏に係る空港等からの航空機の離着陸", "航空交通情報圏に係る空港等からの航空機の離着陸", "民間訓練試験空域における航空機の飛行", "航空運送事業の用に供する航空機の操縦"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 13, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法第 71 条の 2（操縦者の見張り義務）について（a）～（d）のうち、正しいものはいくつあ るか。 （１）～（５）の中から選べ。 （a）航空機の操縦を行なつている者は、航空機の航行中は、いかなる気象状態の下においても、 他の航空機その他の物件と衝突しないように見張りをしなければならない。 （b）航空機の操縦を行なつている者は、航空機の航行中は、航空法第 96 条第 1 項の規定による 国土交通大臣の指示に従つている航行である場合、見張りの義務を負わない。 （c）航空機の操縦の練習を行なつている場合、操縦の練習を行なつている者が見張りの義務を負 うため、その練習を監督する者は、見張りの義務を負わない。 （d）計器飛行等の練習を行なつている場合、計器飛行等の練習を行なつている者及びその練習を 監督する者は、見張りのため他の者が同乗している場合は、計器飛行等の練習及びその練習 の監督に集中するため当該航空機外の物件を視認できない気象状態の下にあるとないとにか かわらず、見張りの義務を負わない。',
  '["１つ", "２つ", "３つ", "無し"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 14, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 4, "dropped_text": "４つ", "reason": "answer_was_nashi_drop_yottsu_remap_nashi_to_4", "correct_before": 5, "correct_after": 4, "question_hint": "航空法規#14"}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法第 76 条（報告の義務）で機長が報告しなければならない事項のうち、誤りはどれか。た だし、機長が報告できないときを除く。',
  '["航空機による人の死傷又は物件の損壊", "航空機内にある者の死亡（国土交通省令で定めるものを除く。）又は行方不明", "無線電信又は無線電話により知った他の航空機の墜落、衝突又は火災", "他の航空機との接触"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 15, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '地上移動に関する記述で誤りはどれか。',
  '["前方を十分に監視すること。", "動力装置を制御すること又は制動装置を軽度に使用することにより、速かに且つ安全に停 止することができる速度であること。", "同順位の航空機相互間にあつては、他の航空機を右側に見る航空機が進路を譲らなければ ならない。", "航空機その他の物件と衝突のおそれのある場合は、地上誘導員を配置すること。"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 16, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法第 94 条ただし書きの許可を受けて管制区等を飛行する場合（特別有視界飛行方式による 飛行）、従わなければならない基準（１）～（４）のうち、誤りはどれか。',
  '["雲から離れて飛行すること。", "距離は百十キロメートル、時間は三十分を超えないこと。", "地表又は水面を引き続き視認できる状態で飛行すること。", "当該許可を行う機関に常時連絡を保つこと。"]'::jsonb,
  2,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 17, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '空港等付近の航行方法についての条文で、進路権について誤りはどれか。',
  '["他の航空機に続いて離陸しようとする場合には、その航空機が離陸して着陸帯の末端を通 過する前に、離陸のための滑走を始めないこと。", "他の航空機に続いて着陸しようとする場合には、その航空機が着陸して着陸帯の外に出る 前に、着陸のために当該空港島の区域内に侵入しないこと。", "離陸する他の航空機に続いて着陸しようとする場合には、その航空機が離陸して着陸帯の 中間を通過する前に、着陸のために当該空港等の区域内に進入しないこと。", "着陸する他の航空機に続いて離陸しようとする場合には、その航空機が着陸して着陸帯の 外に出る前に、離陸のための滑走を始めないこと。"]'::jsonb,
  3,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 18, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法第 97 条（飛行計画及びその承認）について（a）～（d）のうち、正しいものはいくつある か。 （１）～（５）の中から選べ。 （a）全ての航空機は、飛行しようとするときは飛行計画を通報しなければならない。 （b）飛行計画の通報時に搭乗者の総人数が確定していない場合は「TBN」と記入して後刻通報す る。 （c）パッセンジャーストップを伴う飛行計画を通報する場合は、離陸から着陸までの各飛行区間 ごとに、別葉として作成しなければならない。 （d）所要時間は、出発飛行場の駐機位置から自走で移動を開始するときから目的地飛行場の駐機 位置で停止するまでの時間を通報する。',
  '["１つ", "２つ", "３つ", "４つ"]'::jsonb,
  1,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 19, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": {"from_count": 5, "dropped_index": 5, "dropped_text": "無し", "reason": "drop_fifth_for_four_choice_ui", "correct_unchanged": true}}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

INSERT INTO unified_cpl_questions (
  main_subject, sub_subject, question_text, options, correct_answer,
  explanation, source_documents, difficulty_level, importance_score,
  appearance_frequency, verification_status, tags, exam_type, applicable_exams
) VALUES (
  '航空法規',
  'CBT例題/未分類',
  '航空法施行規則第 209 条の 2（航空情報）に定められる航空情報の内容（１）～（４）のうち 誤りはどれか。',
  '["空港等及び航空保安施設の供用の開始、休止、再開及び廃止、これらの施設の重要な変更 その他これらの施設の運用に関する事項", "航空交通管制に関する事項", "ロケツト、花火等の打上げ、航空機の集団飛行その他航空機の飛行に影響を及ぼすおそれ のある事項", "重大インシデントに関する事項"]'::jsonb,
  4,
  NULL,
  '{"sources": [{"type": "mlit_sample", "year": 2026, "month": 6, "question_no": 20, "main_subject": "航空法規", "file": "001761087.pdf", "edition": "CPL-airplane-sample"}], "weight": 2.0, "originality": "official", "choice_adaptation": null}'::jsonb,
  3,
  6.0,
  1,
  'verified',
  ARRAY['CPL', '例題集', '2026年6月', '航空法規', 'mlit_sample']::text[],
  'CPL',
  ARRAY['CPL']::text[]
);

COMMIT;